language: ruby
rvm:
  - 2.1.1
bundler_args: --without production  --binstubs
before_script:
  - mysql -e 'create database myl_test'
  - touch log/resque_base.log log/resque_worker.log log/newrelic_agent.log log/production.log
before_install:
  - gem update --system
  - gem --version
  - sudo apt-get update -qq
after_install:
  - bundle-audit update
  - bundle-audit
services:
  - redis-server
  - mysql
