language: ruby
rvm:
  # - 2.1
  - rbx-2.3.0
bundler_args: --without production  --binstubs
before_script:
  - mysql -e 'create database myl_test'
before_install:
  - gem update --system
  - gem --version
  # - sudo apt-get update -qq
after_install:
  - bundle-audit update
  - bundle-audit
services:
  - redis-server
  - mysql
