language: ruby
rvm:
  - 2.1.1
bundler_args: --without production  --binstubs
before_install:
  - gem update --system
  - gem --version
  - sudo apt-get update -qq
  - sudo apt-get upgrade -qq
after_install:
  - bundle-audit update
  - bundle-audit
