require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe BitPayClientsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # BitPayClient. As you add validations to BitPayClient, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BitPayClientsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all bit_pay_clients as @bit_pay_clients" do
      bit_pay_client = BitPayClient.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:bit_pay_clients)).to eq([bit_pay_client])
    end
  end

  describe "GET #show" do
    it "assigns the requested bit_pay_client as @bit_pay_client" do
      bit_pay_client = BitPayClient.create! valid_attributes
      get :show, {:id => bit_pay_client.to_param}, valid_session
      expect(assigns(:bit_pay_client)).to eq(bit_pay_client)
    end
  end

  describe "GET #new" do
    it "assigns a new bit_pay_client as @bit_pay_client" do
      get :new, {}, valid_session
      expect(assigns(:bit_pay_client)).to be_a_new(BitPayClient)
    end
  end

  describe "GET #edit" do
    it "assigns the requested bit_pay_client as @bit_pay_client" do
      bit_pay_client = BitPayClient.create! valid_attributes
      get :edit, {:id => bit_pay_client.to_param}, valid_session
      expect(assigns(:bit_pay_client)).to eq(bit_pay_client)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new BitPayClient" do
        expect {
          post :create, {:bit_pay_client => valid_attributes}, valid_session
        }.to change(BitPayClient, :count).by(1)
      end

      it "assigns a newly created bit_pay_client as @bit_pay_client" do
        post :create, {:bit_pay_client => valid_attributes}, valid_session
        expect(assigns(:bit_pay_client)).to be_a(BitPayClient)
        expect(assigns(:bit_pay_client)).to be_persisted
      end

      it "redirects to the created bit_pay_client" do
        post :create, {:bit_pay_client => valid_attributes}, valid_session
        expect(response).to redirect_to(BitPayClient.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved bit_pay_client as @bit_pay_client" do
        post :create, {:bit_pay_client => invalid_attributes}, valid_session
        expect(assigns(:bit_pay_client)).to be_a_new(BitPayClient)
      end

      it "re-renders the 'new' template" do
        post :create, {:bit_pay_client => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested bit_pay_client" do
        bit_pay_client = BitPayClient.create! valid_attributes
        put :update, {:id => bit_pay_client.to_param, :bit_pay_client => new_attributes}, valid_session
        bit_pay_client.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested bit_pay_client as @bit_pay_client" do
        bit_pay_client = BitPayClient.create! valid_attributes
        put :update, {:id => bit_pay_client.to_param, :bit_pay_client => valid_attributes}, valid_session
        expect(assigns(:bit_pay_client)).to eq(bit_pay_client)
      end

      it "redirects to the bit_pay_client" do
        bit_pay_client = BitPayClient.create! valid_attributes
        put :update, {:id => bit_pay_client.to_param, :bit_pay_client => valid_attributes}, valid_session
        expect(response).to redirect_to(bit_pay_client)
      end
    end

    context "with invalid params" do
      it "assigns the bit_pay_client as @bit_pay_client" do
        bit_pay_client = BitPayClient.create! valid_attributes
        put :update, {:id => bit_pay_client.to_param, :bit_pay_client => invalid_attributes}, valid_session
        expect(assigns(:bit_pay_client)).to eq(bit_pay_client)
      end

      it "re-renders the 'edit' template" do
        bit_pay_client = BitPayClient.create! valid_attributes
        put :update, {:id => bit_pay_client.to_param, :bit_pay_client => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested bit_pay_client" do
      bit_pay_client = BitPayClient.create! valid_attributes
      expect {
        delete :destroy, {:id => bit_pay_client.to_param}, valid_session
      }.to change(BitPayClient, :count).by(-1)
    end

    it "redirects to the bit_pay_clients list" do
      bit_pay_client = BitPayClient.create! valid_attributes
      delete :destroy, {:id => bit_pay_client.to_param}, valid_session
      expect(response).to redirect_to(bit_pay_clients_url)
    end
  end

end
